<?php
function sr_pill(string $text, string $kind='status'): string { return '<span class="pill '.$kind.' '.sr_status_class($text).'">'.sr_e($text).'</span>'; }
function sr_hero(string $eyebrow, string $title, string $body): void { echo '<section class="hero"><p class="eyebrow">'.sr_e($eyebrow).'</p><h1>'.sr_e($title).'</h1><p>'.sr_e($body).'</p></section>'; }
function sr_metric(string $label, string $value, string $href='', string $note=''): void { echo '<a class="metric" href="'.sr_e($href ?: '#').'"><strong>'.sr_e($value).'</strong><span>'.sr_e($label).'</span><small>'.sr_e($note).'</small></a>'; }
function sr_record_card(array $r): void { echo '<article class="record-card"><div class="record-top"><a class="record-id" href="'.sr_e(sr_record_url($r['record_id'])).'">'.sr_e($r['record_id']).'</a>'.sr_pill($r['status']).'</div><h3><a href="'.sr_e(sr_record_url($r['record_id'])).'">'.sr_e($r['title']).'</a></h3><p>'.sr_e(strlen($r['description']) > 220 ? substr($r['description'], 0, 220) . '…' : $r['description']).'</p><dl><div><dt>Timeline</dt><dd><a href="'.sr_e(sr_url(['page'=>'explore','family'=>$r['family']])).'">'.sr_e($r['timeline_moment_id_or_gen']).'</a></dd></div><div><dt>Owner</dt><dd>'.sr_e($r['owner_or_responsible_role']).'</dd></div><div><dt>Rights</dt><dd>'.sr_pill($r['rights_status'],'risk').'</dd></div><div><dt>Safety</dt><dd>'.sr_pill($r['safety_status'],'risk').'</dd></div><div><dt>Source</dt><dd><a href="'.sr_e(sr_source_url($r['source_file'])).'">'.sr_e($r['source_file']).'</a></dd></div></dl><a class="button" href="'.sr_e(sr_record_url($r['record_id'])).'">View owner summary + raw data</a></article>'; }
function sr_filters(): void { echo '<form class="filters" method="get"><input type="hidden" name="page" value="explore"><label>Search <input name="q" value="'.sr_e($_GET['q'] ?? '').'" placeholder="song, fixture, rights, task..."></label>'; foreach (['family'=>'Timeline family','source_file'=>'JSON source','section'=>'Section','status'=>'Status','rights_status'=>'Rights','safety_status'=>'Safety'] as $field=>$label) { echo '<label>'.sr_e($label).'<select name="'.sr_e($field).'"><option value="">All</option>'; foreach (sr_option_values($field) as $v) echo '<option value="'.sr_e($v).'" '.(((string)($_GET[$field]??'')===$v)?'selected':'').'>'.sr_e($v).'</option>'; echo '</select></label>'; } echo '<button>Apply</button><a class="button ghost" href="?page=explore">Reset</a></form>'; }

function sr_data_alert(): void { $status = sr_data_status(); if ($status['json_count'] > 0) return; echo '<section class="data-alert"><h2>No JSON data found</h2><p>The app looked for <code>*.json</code> files but found none. Put the data at <code>secondrendition/data/ssot/</code> for normal deployment, or copy JSON files directly into <code>secondrendition/data/</code>.</p><details><summary>Checked folders</summary><ul>'; foreach ($status['candidate_roots'] as $root) echo '<li><code>'.sr_e($root).'</code></li>'; echo '</ul></details></section>'; }
function sr_raw_block($data, string $title='Raw JSON'): void { echo '<details class="raw"><summary>'.sr_e($title).'</summary><pre>'.sr_e(json_encode($data, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre></details>'; }
function sr_linked_file(string $file): string { $base=basename($file); if (str_ends_with($base,'.json') && is_readable(sr_ssot_root().'/'.$base)) return '<a href="'.sr_e(sr_source_url($base)).'">'.sr_e($file).'</a>'; return '<code>'.sr_e($file).'</code>'; }
