<?php
function ac_pill(string $text,string $kind='status'): string { return '<span class="pill '.$kind.' '.ac_status_class($text).'">'.ac_e($text).'</span>'; }
function ac_hero(string $eyebrow,string $title,string $body): void { echo '<section class="hero"><p class="eyebrow">'.ac_e($eyebrow).'</p><h1>'.ac_e($title).'</h1><p>'.ac_e($body).'</p></section>'; }
function ac_metric(string $label,string $value,string $note=''): void { echo '<article class="metric"><strong>'.ac_e($value).'</strong><span>'.ac_e($label).'</span><small>'.ac_e($note).'</small></article>'; }
function ac_alert_strip(array $records): void { if(ac_route_was_invalid()) echo '<section class="alert-strip warning"><b>Route fallback</b><span>Unknown page requested; dashboard loaded.</span></section>'; if($f=ac_flash()) echo '<section class="alert-strip '.ac_e($f['type']).'"><b>'.($f['type']==='error'?'Needs attention':'Saved').'</b><span>'.ac_e($f['message']).'</span></section>'; $rights=count(ac_filter_records(fn($r)=>preg_match('/unknown|needs|reference|prohibited/i',$r['rights_status']))); $safety=count(ac_filter_records(fn($r)=>preg_match('/needs|venue|unsafe/i',$r['safety_status']))); echo '<section class="alert-strip" aria-label="Risk alerts"><b>Publication gates active</b><span>Rights items to review: '.$rights.'</span><span>Safety/venue items to review: '.$safety.'</span><span>cue.txt remains draft/proposed until migrated</span><span>No official affiliation or protected marks unless cleared</span></section>'; }
function ac_row_attrs(array $r): string { $map=['data-status'=>$r['status'],'data-priority'=>$r['priority'],'data-rights'=>$r['rights_status'],'data-safety'=>$r['safety_status'],'data-public'=>$r['public_private_flag'],'data-role'=>$r['owner_or_responsible_role'],'data-gate'=>ac_public_gate($r),'data-family'=>$r['family'],'data-source'=>$r['source_file'],'data-search'=>strtolower(implode(' ',[$r['record_id'],$r['title'],$r['section'],$r['category'],$r['status'],$r['rights_status'],$r['safety_status'],$r['owner_or_responsible_role'],$r['description']]))]; $out=''; foreach($map as $k=>$v) $out.=' '.$k.'="'.ac_e($v).'"'; return $out; }
function ac_record_table(array $rows, bool $compact=false): void { echo '<div class="table-wrap"><table class="data-table" data-filter-table><thead><tr><th>ID</th><th>Title</th><th>Timeline</th><th>Status</th><th>Priority</th><th>Owner</th><th>Rights</th><th>Safety</th><th>Gate</th></tr></thead><tbody>'; foreach($rows as $r){ echo '<tr'.ac_row_attrs($r).'>'; echo '<td><a href="?page=record-detail&id='.rawurlencode($r['record_id']).'">'.ac_e($r['record_id']).'</a></td><td>'.ac_e($r['title']).'</td><td>'.ac_pill($r['timeline_moment_id_or_gen'],'timeline').'</td><td>'.ac_pill($r['status']).'</td><td>'.ac_e($r['priority']).'</td><td>'.ac_e($r['owner_or_responsible_role']).'</td><td>'.ac_pill($r['rights_status'],'risk').'</td><td>'.ac_pill($r['safety_status'],'risk').'</td><td>'.ac_pill(ac_public_gate($r),'gate').'</td></tr>'; } echo '</tbody></table><p class="no-results" hidden>No matching records.</p></div>'; }
function ac_filters(): void { $o=ac_options(); echo '<section class="filters" data-filter-controls><label>Filter table <input data-table-search type="search" placeholder="Search records, roles, gates"></label>'; $filters=['status'=>'status','priority'=>'priority','rights'=>'rights','safety'=>'safety','public'=>'public','role'=>'roles']; foreach($filters as $data=>$k){ echo '<label>'.ac_e($data).'<select data-column-filter="'.ac_e($data).'"><option value="">All</option>'; foreach($o[$k] as $v) echo '<option value="'.ac_e($v).'">'.ac_e($v).'</option>'; echo '</select></label>'; } echo '<label>gate<select data-column-filter="gate"><option value="">All</option><option value="open">open</option><option value="blocked">blocked</option></select></label><button type="button" data-reset-filters>Reset</button><span class="result-count" data-result-count></span></section>'; }
function ac_record_cards(array $rows): void { echo '<div class="card-grid">'; foreach($rows as $r){ echo '<article class="card"'.ac_row_attrs($r).'><div class="card-top"><code>'.ac_e($r['record_id']).'</code>'.ac_pill($r['status']).'</div><h3>'.ac_e($r['title']).'</h3><p>'.ac_e($r['description']).'</p><p>'.ac_pill($r['timeline_moment_id_or_gen'],'timeline').' '.ac_pill($r['rights_status'],'risk').' '.ac_pill($r['safety_status'],'risk').'</p><a class="button" href="?page=record-detail&id='.rawurlencode($r['record_id']).'">Open/edit</a></article>'; } echo '</div>'; }
function ac_record_detail_panel(array $r): void { echo '<section class="panel record-readout"><h2>Record data</h2><dl class="record-readout-grid">'; foreach(['title'=>'Title','section'=>'Section','category'=>'Category','timeline_moment_id_or_gen'=>'Timeline / GEN','status'=>'Status','priority'=>'Priority','owner_or_responsible_role'=>'Owner / role','public_private_flag'=>'Public/private','rights_status'=>'Rights','safety_status'=>'Safety','source_type'=>'Source type','source_file'=>'Source file','last_updated'=>'Last updated'] as $field=>$label){ echo '<div><dt>'.ac_e($label).'</dt><dd>'.ac_e(ac_text($r[$field]??'')).'</dd></div>'; } echo '</dl><h3>Description</h3><p>'.nl2br(ac_e($r['description']??'')).'</p>'; if(trim((string)($r['notes']??''))!=='') echo '<h3>Notes</h3><p>'.nl2br(ac_e($r['notes'])).'</p>'; echo '</section>'; }
function ac_checklist(array $items): void { echo '<ul class="checklist">'; foreach($items as $it) echo '<li><input type="checkbox"> '.ac_e($it).'</li>'; echo '</ul>'; }
