<?php
function tr_pill(string $text, string $kind='status'): string { return '<span class="pill '.$kind.' '.tr_status_class($text).'">'.tr_e($text).'</span>'; }
function tr_hero(string $eyebrow, string $title, string $body): void { echo '<section class="hero"><p class="eyebrow">'.tr_e($eyebrow).'</p><h1>'.tr_e($title).'</h1><p>'.tr_e($body).'</p></section>'; }
function tr_metric(string $label, string $value, string $href='', string $note=''): void { echo '<a class="metric" href="'.tr_e($href ?: '#').'"><strong>'.tr_e($value).'</strong><span>'.tr_e($label).'</span><small>'.tr_e($note).'</small></a>'; }
function tr_record_card(array $r): void { echo '<article class="record-card"><div class="record-top"><a class="record-id" href="'.tr_e(tr_record_url($r['record_id'])).'">'.tr_e($r['record_id']).'</a>'.tr_pill($r['status']).'</div><h3><a href="'.tr_e(tr_record_url($r['record_id'])).'">'.tr_e($r['title']).'</a></h3><p>'.tr_e(strlen($r['description']) > 220 ? substr($r['description'], 0, 220) . '…' : $r['description']).'</p><dl><div><dt>Timeline</dt><dd><a href="'.tr_e(tr_url(['page'=>'explore','family'=>$r['family']])).'">'.tr_e($r['timeline_moment_id_or_gen']).'</a></dd></div><div><dt>Owner</dt><dd>'.tr_e($r['owner_or_responsible_role']).'</dd></div><div><dt>Rights</dt><dd>'.tr_pill($r['rights_status'],'risk').'</dd></div><div><dt>Safety</dt><dd>'.tr_pill($r['safety_status'],'risk').'</dd></div><div><dt>Source</dt><dd><a href="'.tr_e(tr_source_url($r['source_file'])).'">'.tr_e($r['source_file']).'</a></dd></div></dl><a class="button" href="'.tr_e(tr_record_url($r['record_id'])).'">Open full detail</a></article>'; }
function tr_filters(): void { echo '<form class="filters" method="get"><input type="hidden" name="page" value="explore"><label>Search <input name="q" value="'.tr_e($_GET['q'] ?? '').'" placeholder="song, fixture, rights, task..."></label>'; foreach (['family'=>'Timeline family','source_file'=>'JSON source','section'=>'Section','status'=>'Status','rights_status'=>'Rights','safety_status'=>'Safety'] as $field=>$label) { echo '<label>'.tr_e($label).'<select name="'.tr_e($field).'"><option value="">All</option>'; foreach (tr_option_values($field) as $v) echo '<option value="'.tr_e($v).'" '.(((string)($_GET[$field]??'')===$v)?'selected':'').'>'.tr_e($v).'</option>'; echo '</select></label>'; } echo '<button>Apply</button><a class="button ghost" href="?page=explore">Reset</a></form>'; }
function tr_data_alert(): void { $status = tr_data_status(); if ($status['json_count'] > 0) return; echo '<section class="data-alert"><h2>No JSON data found</h2><p>The app looked for <code>*.json</code> files but found none. Put the data at <code>thirdrendition/data/ssot/</code> for normal deployment.</p><details><summary>Checked folders</summary><ul>'; foreach ($status['candidate_roots'] as $root) echo '<li><code>'.tr_e($root).'</code></li>'; echo '</ul></details></section>'; }
function tr_raw_block($data, string $title='Raw JSON'): void { echo '<details class="raw"><summary>'.tr_e($title).'</summary><pre>'.tr_e(json_encode($data, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre></details>'; }
function tr_linked_file(string $file): string { $base=basename($file); if (str_ends_with($base,'.json') && is_readable(tr_ssot_root().'/'.$base)) return '<a href="'.tr_e(tr_source_url($base)).'">'.tr_e($file).'</a>'; return '<code>'.tr_e($file).'</code>'; }
function tr_owner_table(array $rows, string $empty='No records found.'): void { if (!$rows) { echo '<p class="muted">'.tr_e($empty).'</p>'; return; } echo '<div class="table-wrap"><table class="owner-table"><thead><tr><th>Item</th><th>Timeline</th><th>Section</th><th>Owner</th><th>Rights</th><th>Safety</th><th>Source</th></tr></thead><tbody>'; foreach ($rows as $r) echo '<tr><td><a href="'.tr_e(tr_record_url($r['record_id'])).'"><b>'.tr_e($r['title']).'</b><small>'.tr_e($r['record_id']).'</small></a></td><td>'.tr_e($r['timeline_moment_id_or_gen']).'</td><td>'.tr_e($r['section']).'</td><td>'.tr_e($r['owner_or_responsible_role']).'</td><td>'.tr_pill($r['rights_status'],'risk').'</td><td>'.tr_pill($r['safety_status'],'risk').'</td><td><a href="'.tr_e(tr_source_url($r['source_file'])).'">'.tr_e($r['source_file']).'</a></td></tr>'; echo '</tbody></table></div>'; }
function tr_collection_filter(string $page): void { echo '<form class="filters compact" method="get"><input type="hidden" name="page" value="'.tr_e($page).'"><label>Filter this page <input name="q" value="'.tr_e($_GET['q'] ?? '').'" placeholder="type a fixture, cue, source, status..."></label><button>Filter</button><a class="button ghost" href="?page='.tr_e($page).'">Reset</a></form>'; }
